/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.CS2263_Acquire_Project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void canStartGame(){

    }

    @Test void canEndGame(){

    }

    @Test void canInitGame(){

    }

    @Test void canInitScoreboard(){

    }

    @Test void canInitPlayer(){

    }

    @Test void canInitTStack(){

    }

    @Test void canDisplayGameboard(){

    }

    @Test void canDisplayScoreboard(){

    }

    @Test void canDisplayHand(){

    }

}
